version: '3.7'

services:
  ruby_on_rails:
    build:
      context: .
    image: ruby_on_rails    

    volumes:
      - .:/app
    # make the container keep running
    stdin_open: true
    tty: true
    command: /bin/bash
